### ISSUE TITLE
Create wiki with basic documentation

### ISSUE THREAD

**Issue by mkroetzsch** [knowsys/vlog4j#100]
The basic content of the wiki should be:
- [x] Short introduction and feature overview
- [x] Publications (what to cite on VLog4j)
- [x] A page about using VLog4j via Maven (mainly a link to the example project)
- [x] A page about using VLog4j as a stand-alone client
- [x] A page about the KB syntax
- [ ] A page about test datasets and benchmarks that people might want to try

**Comment by mkroetzsch** [comment]
A wiki has been created, but it seems more could be done. What is the current status? Where is help needed?

**Comment by larryjgonzalez** [comment]
5 points over 6 have been addressed

Following up on out meeting today, I'm closing this issue and creating a new one only for point 6. *Create a page about datasets and benchmarks*
