### ISSUE TITLE
Core: obtain materialised chase

### ISSUE THREAD

**Issue by mkroetzsch** [knowsys/vlog4j#135]
There should be a way of getting access to all inferred facts, without having to issue queries for each predicate. This could be presented as a stream, collection, or iterator over Literal objects (to be discussed), and it could be provided as a single method of the Reasoner, or possibly through a dependent object ("Chase") that the Reasoner can return and through which this (and other) modes of access are possible.

**Comment by irina-dragoste** [comment]
Possible solutions:

- [ ] export all facts into a file in our RLS syntax, encoded as facts
- [ ] export all facts into a set of CSVDataSourceDeclarations for each IDB and/or EDB.

**Comment by irina-dragoste** [comment]
note that vlog4j-base class karmaresearch.vlog.VLog already supports method

```
/**
     * Creates a CSV file at the specified location, for the specified
     * predicate.
     *
     * @param predicateName
     *            the predicate name
     * @param fileName
     *            the location
     * @exception NotStartedException
     *                is thrown when vlog is not started yet, or materialization
     *                has not run yet
     * @exception IOException
     *                is thrown when the file could not be written for some
     *                reason
     */
    public native void writePredicateToCsv(String predicateName,
            String fileName) throws NotStartedException, IOException;

```

**Comment by irina-dragoste** [comment]
Solution:
- Write all chase facts into an OutputStream in VLog4j Fact syntax
- export all facts chase (without duplicates), not just inferred facts
- avoid creating Fact objects from query results, but have a String representation of query results that is the same as for the corresponding Facts. 
- unit tests could check that the exported chase result is readable
- for handling the String representation of a QueryResult and its Predicate, use Serializer class / a different class than VLogReasoner
- vLog- specific dependencies should not be in a Serializer class
