### ISSUE TITLE
Core: throw ReasonerStateException when attempting to use a closed reasoner.

### ISSUE THREAD

**Issue by irina-dragoste** [knowsys/vlog4j#26]
After _**close()**_ method has been called on a _**Reasoner**_ object, all other public methods of  _**Reasoner**_ except _**close()**_ should return a _**ReasonerStateException**_.

**Comment by Adrian-Bielefeldt** [comment]
I would implement this if nobody else is working on it.

**Comment by irina-dragoste** [comment]
> I would implement this if nobody else is working on it.

@Adrian-Bielefeldt nobody that I know of is working on this issue.

**Comment by Adrian-Bielefeldt** [comment]
Looking at the additional changes in tests and examples resulting from letting all public **_Reasoner_** methods throw a _**ReasonerStateException**_, I was wondering if it would be more user-friendly to only throw the exception when using methods that access the `VLog`-variable directly. Methods that simply don't make sense on a closed **_Reasoner_** like `setReasoningTimeout` could raise a warning. Finally, the getters could sensibly be executed on a closed **_Reasoner_** and should probably not be modified at all.

**Comment by Adrian-Bielefeldt** [comment]
A question: With the following call order
`reasoner.close()`
`reasoner.resetReasoner()`
the _**Reasoner**_ seems to work as intended. Are there any caveats hiding in specific call orders? If not I would exclude the reset method from being blocked by `reasoner.close()`

**Comment by irina-dragoste** [comment]
> Looking at the additional changes in tests and examples resulting from letting all public **_Reasoner_** methods throw a _**ReasonerStateException**_, I was wondering if it would be more user-friendly to only throw the exception when using methods that access the `VLog`-variable directly. Methods that simply don't make sense on a closed **_Reasoner_** like `setReasoningTimeout` could raise a warning. Finally, the getters could sensibly be executed on a closed **_Reasoner_** and should probably not be modified at all.

I agree.

**Comment by irina-dragoste** [comment]
> A question: With the following call order
> `reasoner.close()`
> `reasoner.resetReasoner()`
> the _**Reasoner**_ seems to work as intended. Are there any caveats hiding in specific call orders? If not I would exclude the reset method from being blocked by `reasoner.close()`

On the `vLog`-variable of class `karmaresearch.vlog.VLog`, repeated calls of `start` lead to an `AlreadyStartedException`. That is why `stop` has to be called before a new `start` call. A `stop` call on an not-yet-started or already stopped reasoners are legal. There is no hidden reason for not allowing `resetReasoning` after `close`, it can be allowed.
Perhaps it is best to follow best practices of classes that implement `AutoCloseable`, and what method calls are legal after `close` has been called explicitly.

**Comment by irina-dragoste** [comment]
solved by pull request #59
