### ISSUE TITLE
Core: modify the knowledge base internally to ensure EDB-IDB separation .

### ISSUE THREAD

**Issue by irina-dragoste** [knowsys/vlog4j#32]
Ensure EDB-IDB separation by modifying the reasoner knowledge base internally.
For each [`Predicate`](https://knowsys.github.io/vlog4j/org/semanticweb/vlog4j/core/model/api/Predicate.html) P appearing in a rule body:
1. modify the facts predicates by by renaming _P_  to src_P.
2. add source-to-target rules src_P -> P . 
This way, for any set of rules and facts in a knowledge base, EDB-IDB separation will be ensured automatically, without requiring the user to modify the knowledge base.

**Comment by mkroetzsch** [comment]
Fixed in #83.
