### ISSUE TITLE
Core: modify the knowledge base internally to allow multiple data sources for the same predicate.

### ISSUE THREAD

**Issue by irina-dragoste** [knowsys/vlog4j#33]
Modify the reasoner knowledge base internally, to allow multiple data sources for the same [`Predicate`](https://knowsys.github.io/vlog4j/org/semanticweb/vlog4j/core/model/api/Predicate.html).

 For each [`Predicate`](https://knowsys.github.io/vlog4j/org/semanticweb/vlog4j/core/model/api/Predicate.html) _P_ appearing in facts/associated to a [`DataSource`](https://knowsys.github.io/vlog4j/org/semanticweb/vlog4j/core/reasoner/DataSource.html):
1. Modify the facts predicates, renaming  _P_  to _dsid_P_  with dsid unique for the data source instance associated to the predicate.
2. Add rule _dsid_P -> P_.

This way, for any set of rules and facts in a knowledge base, having one data source  per EDB predicate will be ensured automatically, without requiring the user to modify the knowledge base.

**Comment by mkroetzsch** [comment]
Fixed in #83
