### ISSUE TITLE
SIGSEGV 

### ISSUE THREAD

**Issue by Adrian-Bielefeldt** [knowsys/vlog4j#34]
Hello everyone,

I have an error when executing reasoning. The error is
SIGSEGV (0xb) at pc=0x00007f34fff347e8, pid=23224, tid=0x00007f3553b5d700
I have tried to get it down to a minimal example, found [here](https://github.com/Adrian-Bielefeldt/wcd/blob/master/src/main/java/experiment/MinimalExample.java). The offending rule seems to be the one in line 69.

Another problem that might be related (or a misunderstanding on my part) is the rule in line 73. This should result in a derivation as far as I can see, but it does not.

Greetings,

Adrian Bielefeldt

**Comment by mkroetzsch** [comment]
Thanks, this sounds like a problem caused by the underlying C++ code. 
@jrbn @CerielJacobs Can you comment?

**Comment by CerielJacobs** [comment]
I fixed these issues in the underlying C++ code (I hope). Rebuilding vlog4j with the build-vlog-library.sh script should do the trick.
