### ISSUE TITLE
Request: Export VLog logs to java

### ISSUE THREAD

**Issue by Adrian-Bielefeldt** [knowsys/vlog4j#35]
Hello everyone,

as far as I can see, the logging information from VLog (runtime materialization, total # derivations, iterations) are not accessible from the Java side. Would it be possible to make them available? I am trying to compare different modelling approaches and this would be very helpful.

Thanks,

Adrian

**Comment by irina-dragoste** [comment]
Hello, vlog4j-core **Reasoner** interface contains methods for setting the log level for the reasoner, and a log file to which the logging will be redirected from system output. The information you request ( (runtime materialization, total # derivations, iterations) correspond to INFO logging level. If a file already exists at the given log file path, it will be overwritten with the logging information

I have pushed on the vlog4j-examples module an example class for configuring log information (**ConfigureReasonerLogging.java**). I hope it provides all the information you need
