### ISSUE TITLE
Maximum cardinality

### ISSUE THREAD

**Issue by Adrian-Bielefeldt** [knowsys/vlog4j#41]
I receive the following (rather clear) error:

ERROR  Need to recompile the program to support larger cardinalities 37

I am aware that predicates with arity 37 are probably not a good idea, but until I have a better idea, I would like to try whether this works or not. What do I need to do to be able to work with larger cardinalities?

**Comment by irina-dragoste** [comment]
This limitation is enforced by the C++ code. @jrbn @CerielJacobs, can you comment?

If you need to run a program that contains predicate with high arities, you can re-write the rules and facts by splitting predicates into fresh predicates with smaller arity, like in reification.

For each **fact** over a predicate, you need to introduce a **fresh constant** identifying the fact, that binds the lower-arity atoms together: fact P(a,b,c,d,e) will become the conjunction of facts P1(a,b,fact1), P2(c,d,fact1), P3(e,fact1).

Then, atom P(?x,?y,?z,?t,?u) in a **rule** becomes the conjunction of atoms linked by the same fact 
P1(?x,?y,?fact), P2(?z,?t,?fact), P3(?u, ?fact). If the predicate appears in the head of a rule, variable ?fact will be existentially quantified.

**Comment by Adrian-Bielefeldt** [comment]
I was in fact coming from a modelling where everything was split into smaller predicates. I'm creating .csv-files with these facts and splitting them increases the memory needed. Since I am working with more than a 100 million facts, the additional disk usage due to the fact1 is not bearable.

**Comment by irina-dragoste** [comment]
@Adrian-Bielefeldt could you check that this problem is fixed with the new master branch version of Vlog? A unit test i committed checks arities of at most 255, so I would like to close the issue after your confirmation.

**Comment by Adrian-Bielefeldt** [comment]
This issue is resolved.
