### ISSUE TITLE
SIGSEGV

### ISSUE THREAD

**Issue by Adrian-Bielefeldt** [knowsys/vlog4j#43]
Hello everyone,

I have another bug to report. Unfortunately I have not yet been able to reproduce it in a minimal example, I will add it once I have managed. The error is:

 A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00007fe8a9082680, pid=21804, tid=0x00007fe8c5b69700

 JRE version: OpenJDK Runtime Environment (8.0_181-b13) (build 1.8.0_181-8u181-b13-0ubuntu0.16.04.1-b13)
 Java VM: OpenJDK 64-Bit Server VM (25.181-b13 mixed mode linux-amd64 compressed oops)
 Problematic frame:
 C  [libvlog-core.so+0x100680]  void std::__introsort_loop<__gnu_cxx::__normal_iterator<unsigned char*, std::vector<unsigned char, std::allocator<unsigned char> > >, long, __gnu_cxx::__ops::_Iter_comp_iter<std::reference_wrapper<MITISorter const> > >(__gnu_cxx::__normal_iterator<unsigned char*, std::vector<unsigned char, std::allocator<unsigned char> > >, __gnu_cxx::__normal_iterator<unsigned char*, std::vector<unsigned char, std::allocator<unsigned char> > >, long, __gnu_cxx::__ops::_Iter_comp_iter<std::reference_wrapper<MITISorter const> >)+0xb0
The full log is [hs_err_pid21804.log](https://github.com/knowsys/vlog4j/files/2319510/hs_err_pid21804.log)

**Comment by Adrian-Bielefeldt** [comment]
I am now fairly certain that I will not be able to provide a minimal example since it seems related to the size of the input data.
I have about two dozend .csv-files that have roughly 200 million facts among each other. I load some of these files, perform reasoning and then closing the reasoner. This is repeated multiple times (with different files) and leads to the error at some iterations. If I execute the program multiple times (so shutting it down completely when I would close the reasoner), the error does not appear.

**Comment by mkroetzsch** [comment]
@CerielJacobs Do you think this could be a VLog issue?

**Comment by CerielJacobs** [comment]
It is very likely a VLog issue; however, the log does not give much information, and the bug report does not give input data or rules, so there is not much to go on.
Also, in the meantime several bugs have been fixed, so maybe (wishful thinking) this bug is gone now. Maybe Adrian can try and reproduce it with the latest version of VLog?

Ceriel

**Comment by mkroetzsch** [comment]
@Adrian-Bielefeldt Can you please check?

**Comment by Adrian-Bielefeldt** [comment]
Checking right now, although the calculation will take a bit. I also noticed that I have to correct

> If I execute the program multiple times (so shutting it down completely when I would close the reasoner), the error does not appear.

This does not help (anymore). I am uncertain if it ever solved the problem or or if I made some mistake when running my program.

**Comment by Adrian-Bielefeldt** [comment]
I cannot reproduce this error with the latest VLog-Version. I would close this.
