### ISSUE TITLE
Core: add unit tests for Reasoner#setReasoningTimeout

### ISSUE THREAD

**Issue by irina-dragoste** [knowsys/vlog4j#53]

**Comment by irina-dragoste** [comment]
test cases when:
* reasoning timeout is null
* reasoning timeout is Integer.MAX_INT
* materialisations terminates before timeout, test the output of Reasoner#reason()

**Comment by irina-dragoste** [comment]
@Adrian-Bielefeldt did you already start working on issue #53 ? If so, please assign yourself, and commit your code on a separate branch, making a pull request. If not, please let me know, I will take over the issue.

**Comment by Adrian-Bielefeldt** [comment]
I started working on this, but I do not seem to be able to assign myself to this issue, since I do not have write access to this repository.
