### ISSUE TITLE
Graal: Support Graal data structures

### ISSUE THREAD

**Issue by Adrian-Bielefeldt** [knowsys/vlog4j#61]
Goal: Support [Graal](https://graphik-team.github.io/graal/) data structures for import to reasoner.

Create class GraalImporter
- [x] add conversion from [Graal Atom](https://graphik-team.github.io/graal/1.3.1/javadocs/fr/lirmm/graphik/graal/api/core/Atom.html) to [Vlog4J Atom](https://knowsys.github.io/vlog4j/org/semanticweb/vlog4j/core/model/api/Atom.html)
- [x] add conversion from [Graal Rule](https://graphik-team.github.io/graal/1.3.1/javadocs/fr/lirmm/graphik/graal/api/core/Rule.html) to [Vlog4J Rule](https://knowsys.github.io/vlog4j/org/semanticweb/vlog4j/core/model/api/package-summary.html)
- [x] add import capability from [Graal ConjunctiveQuery](https://graphik-team.github.io/graal/1.3.1/javadocs/fr/lirmm/graphik/graal/api/core/ConjunctiveQuery.html) to VLog4J
  - [x] add conversion from [Graal ConjunctiveQuery](https://graphik-team.github.io/graal/1.3.1/javadocs/fr/lirmm/graphik/graal/api/core/ConjunctiveQuery.html) to [Vlog4J Rule](https://knowsys.github.io/vlog4j/org/semanticweb/vlog4j/core/model/api/package-summary.html), creating a new [Vlog4J Predicate](https://knowsys.github.io/vlog4j/org/semanticweb/vlog4j/core/model/api/Predicate.html) for the result
  - [x] return a [VLog4J Atom](https://knowsys.github.io/vlog4j/org/semanticweb/vlog4j/core/model/api/Atom.html) to be used as a query
- [x] create a Maven module `vlog4j-graal` for the new classes

Further conversions, e.g., Predicates or Constants, are not made public because the [Graal Parser](https://graphik-team.github.io/graal/1.3.1/javadocs/fr/lirmm/graphik/graal/io/dlp/DlgpParser.html) does not support parsing them. [NegativeConstraint](https://graphik-team.github.io/graal/1.3.1/javadocs/fr/lirmm/graphik/graal/api/core/NegativeConstraint.html) is not supported because VLog does not allow for negation.

**Comment by irina-dragoste** [comment]
I have a few questions regarding this issue:
- If there is support for converting a Graal Atoms, Queries and Rules to Vlog4j entities, why is the addition of new methods in [Vlog4j Reasoner interface](https://knowsys.github.io/vlog4j/org/semanticweb/vlog4j/core/reasoner/Reasoner.html) needed (`Reasoner.addFacts()` for Graal Atoms, respectively, `Reasoner.addRules()` for Graal Rules) ? I would advice against flooding the  [Vlog4j Reasoner interface](https://knowsys.github.io/vlog4j/org/semanticweb/vlog4j/core/reasoner/Reasoner.html) with unnecessary methods and dependencies.
- Are this converter classes used in a new Maven module? I would suggest creating a Maven module inside vlog4-parent, called vlog4j-graal, just like vlog4j-owlapi and vlog4j-rdf. This way, we can separate [Graal API](https://graphik-team.github.io/graal/1.3.1/javadocs/overview-summary.html) dependencies from [Vlog4j core Reasoner API](https://knowsys.github.io/vlog4j/org/semanticweb/vlog4j/core/reasoner/package-summary.html)

**Comment by Adrian-Bielefeldt** [comment]
- The additional methods for the `Reasoner` are not necessary and were more of a suggestion. You are right in that it would unnecessarily flood the `Reasoner` as well as prevent separation as per point two
- They will be created in a separate Maven module
