### ISSUE TITLE
Graal: Support import from .dlgp files

### ISSUE THREAD

**Issue by Adrian-Bielefeldt** [knowsys/vlog4j#63]
Extend `GraalToVlog4JModelConverter` to allow parsing of Graal .dlgp files.

- [x] Add method to `GraalToVlog4JModelConverter` accepting a File, InputStream, or Reader and returning an object containing all `Rules`, `Atoms`, and `ConjunctiveGraalQueryToRule` in that file
    - [x] create new `ConvertedDlgpFile` object to hold the Facts, Rules, and Queries parsed from the file
- [x] decide whether to class-cast the results from `Object` or use the `KnowledgeBase` (decided for parsing because queries cannot be extracted from `KnowledgeBase`)

The `DlgpParser` from Graal returns the results from parsing a .dlp file via[`Object next()`](https://graphik-team.github.io/graal/1.3.1/javadocs/fr/lirmm/graphik/graal/io/dlp/DlgpParser.html#next--). While the [dlpg-module documentation](https://graphik-team.github.io/graal/doc/io-dlgp-module) uses this iterator to obtain the facts and rules, I do not think this to be good style.

The only option to more or less get around this would be to use the [`KBBuilder`](https://graphik-team.github.io/graal/1.3.1/javadocs/fr/lirmm/graphik/graal/kb/KBBuilder.html) and [`KnowledgeBase`](https://graphik-team.github.io/graal/1.3.1/javadocs/fr/lirmm/graphik/graal/api/kb/KnowledgeBase.html) to do these class cast for us (we can get Facts and Rules from the `KnowledgeBase`), but this requires dependency on another maven module (`graal-kb`). I would write the `KnowledgeBase` approach for now.

**EDIT:** changed file ending from .dlp to .dlpg. While the examples use .dlp, the format is formally called [DLGP](https://graphik-team.github.io/graal/doc/dlgp).

**EDIT:** changed class names according to [pull request 62](https://github.com/knowsys/vlog4j/pull/62)

**EDIT:** removed `addToReasoner` method goal since adding facts and rules only takes two calls and this way the class is only dependent on the model, not the `Reasoner`.

**EDIT:** removed switch of Exception for `NegativeConstraint` because `GraalConvertException` is already a `RuntimeException`.

**Comment by Adrian-Bielefeldt** [comment]
This is delayed until [issue 10](https://github.com/graphik-team/graal/issues/10) for Graal is resolved.

**Comment by Adrian-Bielefeldt** [comment]
Done, waiting for [pull request 62](https://github.com/knowsys/vlog4j/pull/62).

**Comment by irina-dragoste** [comment]
I would advice against implementing this functionality in `vlog4j-graal`, and especially against including it in `GraalToVlog4JModelConverter`. 
First of all, the current `GraalToVlog4JModelConverter` contains conversions from graal api model to vlog4j model objects. Adding new functionality for converting files to vlog4j model would break the single responsibility principle of the class.
Secondly, the current methods in `GraalToVlog4JModelConverter` are can be used as building blocks to convert graal .dlgp files to vlog4j knowledge bases, together with the .dlgp parser. To keep this modularity, we would like to only have `vlog4j-graal` depend on `graal-api`. A user can further combine `vlog4j-graal` with the graal dlgp parser (or any resource that would allow for constructing graal model objects, for that matter).
Thirdly, we would have to support reading directly from files, strings, input streams, readers etc. This only floods the code and makes it difficult to maintain. As long as we provide the building blocks for converting core graal objects, it is up to the user how these objects are obtain (perhaps, in practice, a user would want to combine several files, as well as java objects, into a knowledge base).

However, we would want to have an example in `vlog4j-examples`, of how a .dlgp can be parsed, imported into vlog4j, and reasoner over.
