### ISSUE TITLE
unstable addition of facts via owlToRulesConverter.addOntology

### ISSUE THREAD

**Issue by tholiebig** [knowsys/vlog4j#87]
For some reason facts are ignored when loading a TTL from file via OWL API ontology manager. For instance a larger test file is loaded while a smaller fraction thereof (first 8 lines) is not.

```java
public class LoadTripples {

	public static void main(final String[] args) throws OWLOntologyCreationException, IOException {

		/* load ABox using OWL API */
		final OWLOntologyManager ontologyManager = OWLManager.createOWLOntologyManager();
		final OWLOntology abox = ontologyManager
				.loadOntologyFromOntologyDocument(new File("small.ttl"));

		final OwlToRulesConverter owlToRulesConverter = new OwlToRulesConverter();
		owlToRulesConverter.addOntology(abox);

		System.out.println("Nbr of facts: " + owlToRulesConverter.getFacts().size());

	}
}
```
Test data is attached. vlog4j version as of Aug. 29.

**Comment by tholiebig** [comment]
[large.ttl.zip](https://github.com/knowsys/vlog4j/files/3579517/large.ttl.zip)
[small.ttl.zip](https://github.com/knowsys/vlog4j/files/3579518/small.ttl.zip)

**Comment by irina-dragoste** [comment]
This is not a bug. File _large.ttl_ contains declaration `<http://www.foo.com/test#is-made-of> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2002/07/owl#ObjectProperty> .`, which is missing from _small.ttl_. If axiom properties are not declared, OWL API interprets axioms with these properties as Annotation Assertions.  `vlog4j-owlapi` only transforms Property Assertions to facts.

`public class LoadTripples {

	public static void main(final String[] args) throws OWLOntologyCreationException, IOException {

		/* load ABox using OWL API */
		final OWLOntologyManager ontologyManager = OWLManager.createOWLOntologyManager();
		final OWLOntology abox = ontologyManager.loadOntologyFromOntologyDocument(new File("resources/small.ttl"));

		final OwlToRulesConverter owlToRulesConverter = new OwlToRulesConverter();
		owlToRulesConverter.addOntology(abox);

		System.out.println("Nbr of facts: " + owlToRulesConverter.getFacts().size());

		System.out.println("Nbr of abox axioms: " + abox.aboxAxioms(Imports.EXCLUDED).count());

		System.out.println("Nbr of axioms: " + abox.getAxiomCount());

		final Set<AxiomType> types = new HashSet<AxiomType>();
		abox.axioms().forEach(axiom -> types.add(axiom.getAxiomType()));

		System.out.println("Axiom types: " + types);

	}
}`

**Comment by tholiebig** [comment]
Ok, I see. I need to have schema information about the property types in my ABox.
I want to propose a pure TTL import function that just reads triples.
